[licenses]
allow = ["MIT", "Apache-2.0", "OpenSSL", "ISC"]
unlicensed = "deny"
private = { ignore = true }

[[licenses.exceptions]]
name = "unicode-ident"
allow = ["Unicode-DFS-2016"]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
